import { C, R, S } from './DesignTokens';

export const CustomerProfileStyles = {
    container: { maxWidth: 900, margin: '0 auto', padding: 24 } as React.CSSProperties,
    pageHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 24 } as React.CSSProperties,
    pageTitle: { margin: 0, fontSize: 22, fontWeight: 800, color: C.text } as React.CSSProperties,
    pageSub: { margin: '5px 0 0', fontSize: 13, color: C.textMuted } as React.CSSProperties,
    ghostBtn: { background: 'transparent', color: C.textMuted, border: `1.5px solid ${C.border}`, padding: '9px 18px', borderRadius: R.md, cursor: 'pointer', fontSize: 14, fontWeight: 500 } as React.CSSProperties,
    card: { background: C.card, borderRadius: R.lg, padding: 24, boxShadow: S.md, border: `1px solid ${C.border}`, marginBottom: 20 } as React.CSSProperties,
    profileGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 } as React.CSSProperties,
    label: { fontSize: 11, fontWeight: 700, color: '#94a3b8', textTransform: 'uppercase' as const, letterSpacing: '.5px', marginBottom: 3 } as React.CSSProperties,
    value: { fontSize: 15, fontWeight: 600, color: '#0f172a' } as React.CSSProperties,
    statsGrid: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 14 } as React.CSSProperties,
    statCard: { background: '#f8fafc', borderRadius: 10, padding: '14px 16px', textAlign: 'center' as const } as React.CSSProperties,
    statNumber: { fontSize: 22, fontWeight: 800, color: '#2563eb' } as React.CSSProperties,
    statNumberDanger: { fontSize: 22, fontWeight: 800, color: '#dc2626' } as React.CSSProperties,
    statNumberSuccess: { fontSize: 22, fontWeight: 800, color: '#16a34a' } as React.CSSProperties,
    statLabel: { fontSize: 11, fontWeight: 600, color: '#64748b', textTransform: 'uppercase' as const, letterSpacing: '.3px', marginTop: 4 } as React.CSSProperties,
    table: { width: '100%', borderCollapse: 'collapse' as const } as React.CSSProperties,
    th: { background: '#f8fafc', padding: '9px 12px', textAlign: 'left' as const, fontSize: 11, fontWeight: 600, color: '#64748b', textTransform: 'uppercase' as const, letterSpacing: '.4px', border: `1px solid ${C.border}` } as React.CSSProperties,
    td: { padding: '10px 12px', border: `1px solid ${C.border}`, fontSize: 13, color: '#1e293b' } as React.CSSProperties,
    tdBold: { fontWeight: 600 } as React.CSSProperties,
    tableWrapper: { overflowX: 'auto' as const } as React.CSSProperties,
    loading: { textAlign: 'center' as const, padding: 60, fontSize: 15, color: C.textMuted } as React.CSSProperties,
    noData: { textAlign: 'center' as const, padding: 40, color: '#94a3b8', fontSize: 13 } as React.CSSProperties,
    fineAmount: { color: '#dc2626', fontWeight: 600 } as React.CSSProperties,
    sectionTitle: { fontSize: 15, fontWeight: 700, color: '#0f172a', margin: '0 0 16px' } as React.CSSProperties,
    
    statusBadge: (bg: string, color: string) => ({
        background: bg,
        color,
        padding: '3px 10px',
        borderRadius: 20,
        fontSize: 11,
        fontWeight: 600,
        display: 'inline-block',
    } as React.CSSProperties),
    
    payBadge: (bg: string, color: string) => ({
        background: bg,
        color,
        padding: '3px 10px',
        borderRadius: 20,
        fontSize: 11,
        fontWeight: 600,
        display: 'inline-block',
    } as React.CSSProperties),
    
    headerRow: { display: 'flex', justifyContent: 'space-between', marginBottom: 16 } as React.CSSProperties,
};